apiVersion: v1
kind: Service
metadata:
  name: heart-service
spec:
  type: LoadBalancer
  selector:
    app: heart-api
  ports:
  - port: 80           # Access via http://localhost:80
    targetPort: 8000   # Internal container port